[package]
name = "let-the-ai-fly"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
crossterm = "0.29.0"
tokio = { version = "1.45.1", features = ["net", "macros", "rt-multi-thread", "time", "sync"] }
